services:
  - type: web
    name: quiz-piper-tts
    runtime: python
    rootDir: piper
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT piper_server:APP --timeout 180
    plan: free
